version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: